spring:
  application:
    name: Secure-Task-Management-System
  profiles:
    active: dev

server:
  port: 80

api:
  endpoint:
    base-url: "/api/v1"

app:
  email:
    from: no-reply@task-management.com
